#include "woort.h"

#include "woort_dylib.h"

/* Copy from woodyn. */
#define WOODYN_WOORT_FUNCTION_LIST \
    WOODYN_WRAP(woort_version)                                              \
    WOODYN_WRAP(woort_version_int)                                          \
    WOODYN_WRAP(woort_init)                                                 \
    WOODYN_WRAP(woort_shutdown)                                             \
    WOODYN_WRAP(woort_print_runtime_help)                                   \
    WOODYN_WRAP(woort_console_readline)                                     \
    WOODYN_WRAP(woort_free)                                                 \
    WOODYN_WRAP(woort_stdin_isatty)                                         \
    WOODYN_WRAP(woort_console_getc)                                         \
    WOODYN_WRAP(woort_console_ungetc)                                       \
    WOODYN_WRAP(woort_env_locale_name)                                      \
    WOODYN_WRAP(woort_VMRuntime_create)                                     \
    WOODYN_WRAP(woort_VMRuntime_destroy)                                    \
    WOODYN_WRAP(woort_VMRuntime_weaken)                                     \
    WOODYN_WRAP(woort_GC_mark_weak_vm_manually)                             \
    WOODYN_WRAP(woort_GC_mark_droped_env_manually)                          \
    WOODYN_WRAP(woort_GC_mark_internal_value_manually)                      \
    WOODYN_WRAP(woort_GC_set_internal_value_with_mixed_write_barrier)       \
    WOODYN_WRAP(woort_GC_internal_value_delete_barrier)                     \
    WOODYN_WRAP(woort_GC_allocate)                                          \
    WOODYN_WRAP(woort_GC_allocate_as_root)                                  \
    WOODYN_WRAP(woort_GC_unregister_root)                                   \
    WOODYN_WRAP(woort_GC_mark_addr_manually)                                \
    WOODYN_WRAP(woort_GC_set_addr_with_mixed_write_barrier)                 \
    WOODYN_WRAP(woort_GC_addr_delete_barrier)                               \
    WOODYN_WRAP(woort_GCPin_create)                                         \
    WOODYN_WRAP(woort_GCPin_destroy)                                        \
    WOODYN_WRAP(woort_GCPin_set)                                            \
    WOODYN_WRAP(woort_GCPin_get)                                            \
    WOODYN_WRAP(woort_GCPin_set_dup_boxed)                                  \
    WOODYN_WRAP(woort_GCPin_set_internal)                                   \
    WOODYN_WRAP(woort_GCPin_get_internal)                                   \
    WOODYN_WRAP(woort_GCPin_get_internal_without_barrier)                   \
    WOODYN_WRAP(woort_GCPin_set_dup_boxed_internal)                         \
    WOODYN_WRAP(woort_GC_sync_marking_lock)                                 \
    WOODYN_WRAP(woort_GC_sync_marking_unlock)                               \
    WOODYN_WRAP(woort_VMRuntime_swap)                                       \
    WOODYN_WRAP(woort_VMRuntime_current)                                    \
    WOODYN_WRAP(woort_VMRuntime_get_runtime_error_msg)                      \
    WOODYN_WRAP(woort_VMRuntime_trace_begin)                                \
    WOODYN_WRAP(woort_VMRuntime_trace_next)                                 \
    WOODYN_WRAP(woort_VMRuntime_log_trace)                                  \
    WOODYN_WRAP(woort_VMRuntime_print_backtrace)                            \
    WOODYN_WRAP(woort_CodeEnv_save_binary)                                  \
    WOODYN_WRAP(woort_CodeEnv_restore_binary)                               \
    WOODYN_WRAP(woort_CodeEnv_restore_failed_desc)                          \
    WOODYN_WRAP(woort_CodeEnv_drop)                                         \
    WOODYN_WRAP(woort_CodeEnv_query_function)                               \
    WOODYN_WRAP(woort_CodeEnv_lock)                                         \
    WOODYN_WRAP(woort_CodeEnv_unlock)                                       \
    WOODYN_WRAP(woort_CodeEnv_find_srcloc_by_offset)                        \
    WOODYN_WRAP(woort_CodeEnv_find_offset_by_srcloc)                        \
    WOODYN_WRAP(woort_CodeEnv_foreach_offset_by_srcloc)                     \
    WOODYN_WRAP(woort_CodeEnv_find_function_name_by_offset)                 \
    WOODYN_WRAP(woort_CodeEnv_set_trap)                                     \
    WOODYN_WRAP(woort_CodeEnv_clear_trap)                                   \
    WOODYN_WRAP(woort_CodeEnv_raw_trap)                                     \
    WOODYN_WRAP(woort_CodeEnv_dumps)                                        \
    WOODYN_WRAP(woort_CodeEnv_register_extern_constant)                     \
    WOODYN_WRAP(woort_CodeEnv_find_extern_constant)                         \
    WOODYN_WRAP(woort_CodeEnv_add_extern_lib)                               \
    WOODYN_WRAP(woort_CodeEnv_jit)                                          \
    WOODYN_WRAP(woort_IRCompiler_create)                                    \
    WOODYN_WRAP(woort_IRCompiler_close)                                     \
    WOODYN_WRAP(woort_IRCompiler_intern_string)                             \
    WOODYN_WRAP(woort_IRCompiler_add_function)                              \
    WOODYN_WRAP(woort_IRCompiler_add_constant)                              \
    WOODYN_WRAP(woort_IRCompiler_add_static)                                \
    WOODYN_WRAP(woort_IRCompiler_finish)                                    \
    WOODYN_WRAP(woort_IRFunction_new_vreg)                                  \
    WOODYN_WRAP(woort_IRFunction_get_argument)                              \
    WOODYN_WRAP(woort_IRFunction_get_captured)                              \
    WOODYN_WRAP(woort_IRFunction_new_label)                                 \
    WOODYN_WRAP(woort_IRFunction_fetch_const)                               \
    WOODYN_WRAP(woort_IRFunction_push_srcloc)                               \
    WOODYN_WRAP(woort_IRFunction_pop_srcloc)                                \
    WOODYN_WRAP(woort_IRFunction_set_name)                                  \
    WOODYN_WRAP(woort_IRFunction_record_local_var)                          \
    WOODYN_WRAP(woort_IRCompiler_record_static_var)                         \
    WOODYN_WRAP(woort_IR_NOP)                                               \
    WOODYN_WRAP(woort_IR_MOV)                                               \
    WOODYN_WRAP(woort_IR_LOAD)                                              \
    WOODYN_WRAP(woort_IR_STORE)                                             \
    WOODYN_WRAP(woort_IR_LOADPVALUE)                                        \
    WOODYN_WRAP(woort_IR_STOREPVALUE)                                       \
    WOODYN_WRAP(woort_IR_MKPVALUE)                                          \
    WOODYN_WRAP(woort_IR_PUSHCHK)                                           \
    WOODYN_WRAP(woort_IR_PUSHSTATICCHK)                                     \
    WOODYN_WRAP(woort_IR_POP)                                               \
    WOODYN_WRAP(woort_IR_POPR)                                              \
    WOODYN_WRAP(woort_IR_POPRS)                                             \
    WOODYN_WRAP(woort_IR_ITOR)                                              \
    WOODYN_WRAP(woort_IR_ITOS)                                              \
    WOODYN_WRAP(woort_IR_RTOI)                                              \
    WOODYN_WRAP(woort_IR_RTOS)                                              \
    WOODYN_WRAP(woort_IR_CALLNWO)                                           \
    WOODYN_WRAP(woort_IR_CALLNFP)                                           \
    WOODYN_WRAP(woort_IR_CALLNJIT)                                          \
    WOODYN_WRAP(woort_IR_CALL)                                              \
    WOODYN_WRAP(woort_IR_MKCLOSURE)                                         \
    WOODYN_WRAP(woort_IR_MKVEC)                                             \
    WOODYN_WRAP(woort_IR_MKMAP)                                             \
    WOODYN_WRAP(woort_IR_MKSTRUCT)                                          \
    WOODYN_WRAP(woort_IR_MKUNION)                                           \
    WOODYN_WRAP(woort_IR_BOXDYN)                                            \
    WOODYN_WRAP(woort_IR_UNBOXDYN)                                          \
    WOODYN_WRAP(woort_IR_CHECKDYN)                                          \
    WOODYN_WRAP(woort_IR_PUSHBOXDYN)                                        \
    WOODYN_WRAP(woort_IR_CASTSTO)                                           \
    WOODYN_WRAP(woort_IR_CASTSFROM)                                         \
    WOODYN_WRAP(woort_IR_CASTDYN)                                           \
    WOODYN_WRAP(woort_IR_ASSERTDYN)                                         \
    WOODYN_WRAP(woort_IR_ADDI)                                              \
    WOODYN_WRAP(woort_IR_SUBI)                                              \
    WOODYN_WRAP(woort_IR_MULI)                                              \
    WOODYN_WRAP(woort_IR_CHKDIVIL)                                          \
    WOODYN_WRAP(woort_IR_CHKDIVIR)                                          \
    WOODYN_WRAP(woort_IR_CHKDIVIRZ)                                         \
    WOODYN_WRAP(woort_IR_CHKDIVILR)                                         \
    WOODYN_WRAP(woort_IR_DIVI)                                              \
    WOODYN_WRAP(woort_IR_MODI)                                              \
    WOODYN_WRAP(woort_IR_NEGI)                                              \
    WOODYN_WRAP(woort_IR_LTI)                                               \
    WOODYN_WRAP(woort_IR_GTI)                                               \
    WOODYN_WRAP(woort_IR_LEI)                                               \
    WOODYN_WRAP(woort_IR_GEI)                                               \
    WOODYN_WRAP(woort_IR_EQI)                                               \
    WOODYN_WRAP(woort_IR_NEI)                                               \
    WOODYN_WRAP(woort_IR_ADDR)                                              \
    WOODYN_WRAP(woort_IR_SUBR)                                              \
    WOODYN_WRAP(woort_IR_MULR)                                              \
    WOODYN_WRAP(woort_IR_DIVR)                                              \
    WOODYN_WRAP(woort_IR_MODR)                                              \
    WOODYN_WRAP(woort_IR_NEGR)                                              \
    WOODYN_WRAP(woort_IR_LTR)                                               \
    WOODYN_WRAP(woort_IR_GTR)                                               \
    WOODYN_WRAP(woort_IR_LER)                                               \
    WOODYN_WRAP(woort_IR_GER)                                               \
    WOODYN_WRAP(woort_IR_EQR)                                               \
    WOODYN_WRAP(woort_IR_NER)                                               \
    WOODYN_WRAP(woort_IR_ADDS)                                              \
    WOODYN_WRAP(woort_IR_LTS)                                               \
    WOODYN_WRAP(woort_IR_GTS)                                               \
    WOODYN_WRAP(woort_IR_LES)                                               \
    WOODYN_WRAP(woort_IR_GES)                                               \
    WOODYN_WRAP(woort_IR_EQS)                                               \
    WOODYN_WRAP(woort_IR_NES)                                               \
    WOODYN_WRAP(woort_IR_LAND)                                              \
    WOODYN_WRAP(woort_IR_LOR)                                               \
    WOODYN_WRAP(woort_IR_LNOT)                                              \
    WOODYN_WRAP(woort_IR_LDIDVEC)                                           \
    WOODYN_WRAP(woort_IR_LDIDVECX)                                          \
    WOODYN_WRAP(woort_IR_LDIDSTRUCT)                                        \
    WOODYN_WRAP(woort_IR_LDIDSTRING)                                        \
    WOODYN_WRAP(woort_IR_LDIDDICTI)                                         \
    WOODYN_WRAP(woort_IR_LDIDDICTR)                                         \
    WOODYN_WRAP(woort_IR_LDIDDICTB)                                         \
    WOODYN_WRAP(woort_IR_LDIDDICTX)                                         \
    WOODYN_WRAP(woort_IR_LDIDDICTIX)                                        \
    WOODYN_WRAP(woort_IR_LDIDDICTRX)                                        \
    WOODYN_WRAP(woort_IR_LDIDDICTBX)                                        \
    WOODYN_WRAP(woort_IR_LDIDDICTXX)                                        \
    WOODYN_WRAP(woort_IR_STIDVECI)                                          \
    WOODYN_WRAP(woort_IR_STIDVECR)                                          \
    WOODYN_WRAP(woort_IR_STIDVECB)                                          \
    WOODYN_WRAP(woort_IR_STIDVECX)                                          \
    WOODYN_WRAP(woort_IR_STIDDICTII)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTIR)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTIB)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTIX)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTRI)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTRR)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTRB)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTRX)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTBI)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTBR)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTBB)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTBX)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTXI)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTXR)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTXB)                                        \
    WOODYN_WRAP(woort_IR_STIDDICTXX)                                        \
    WOODYN_WRAP(woort_IR_STIDMAPII)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPIR)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPIB)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPIX)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPRI)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPRR)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPRB)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPRX)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPBI)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPBR)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPBB)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPBX)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPXI)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPXR)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPXB)                                         \
    WOODYN_WRAP(woort_IR_STIDMAPXX)                                         \
    WOODYN_WRAP(woort_IR_STIDSTRUCT)                                        \
    WOODYN_WRAP(woort_IR_UNPACKVEC)                                         \
    WOODYN_WRAP(woort_IR_UNPACKVECX)                                        \
    WOODYN_WRAP(woort_IR_UNPACKVECALL)                                      \
    WOODYN_WRAP(woort_IR_UNPACKVECXALL)                                     \
    WOODYN_WRAP(woort_IR_PUSHIDSTRUCT)                                      \
    WOODYN_WRAP(woort_IR_PUSHIDSTBOXI)                                      \
    WOODYN_WRAP(woort_IR_PUSHIDSTBOXR)                                      \
    WOODYN_WRAP(woort_IR_PUSHIDSTBOXB)                                      \
    WOODYN_WRAP(woort_IR_ASTORE)                                            \
    WOODYN_WRAP(woort_IR_ALOAD)                                             \
    WOODYN_WRAP(woort_IR_CAS)                                               \
    WOODYN_WRAP(woort_IR_PACKARG)                                           \
    WOODYN_WRAP(woort_IR_bind)                                              \
    WOODYN_WRAP(woort_IR_jmp)                                               \
    WOODYN_WRAP(woort_IR_jifinited)                                         \
    WOODYN_WRAP(woort_IR_jcc)                                               \
    WOODYN_WRAP(woort_IR_jccz)                                              \
    WOODYN_WRAP(woort_IR_jcc_lt)                                            \
    WOODYN_WRAP(woort_IR_jcc_le)                                            \
    WOODYN_WRAP(woort_IR_jcc_eq)                                            \
    WOODYN_WRAP(woort_IR_jcc_gt)                                            \
    WOODYN_WRAP(woort_IR_jcc_ge)                                            \
    WOODYN_WRAP(woort_IR_jcc_ne)                                            \
    WOODYN_WRAP(woort_IR_debugtrap)                                         \
    WOODYN_WRAP(woort_IR_panic)                                             \
    WOODYN_WRAP(woort_IR_ret)                                               \
    WOODYN_WRAP(woort_IR_ret_void)                                          \
    WOODYN_WRAP(woort_CodeEnv_set_const_int)                                \
    WOODYN_WRAP(woort_CodeEnv_set_const_real)                               \
    WOODYN_WRAP(woort_CodeEnv_set_const_buffer)                             \
    WOODYN_WRAP(woort_CodeEnv_set_const_script_function)                    \
    WOODYN_WRAP(woort_CodeEnv_set_const_extern_function)                    \
    WOODYN_WRAP(woort_CodeEnv_set_const_script_closure)                     \
    WOODYN_WRAP(woort_CodeEnv_set_const_extern_closure)                     \
    WOODYN_WRAP(woort_CodeEnv_set_const_box_int)                            \
    WOODYN_WRAP(woort_CodeEnv_set_const_box_real)                           \
    WOODYN_WRAP(woort_CodeEnv_set_const_box_bool)                           \
    WOODYN_WRAP(woort_CodeEnv_set_const_struct)                             \
    WOODYN_WRAP(woort_CodeEnv_set_static_value)                             \
    WOODYN_WRAP(woort_CodeEnv_get_static_value)                             \
    WOODYN_WRAP(woort_CodeEnv_get_static_storage_count)                     \
    WOODYN_WRAP(woort_vm_create)                                            \
    WOODYN_WRAP(woort_raise_panic)                                          \
    WOODYN_WRAP(woort_push_reserve)                                         \
    WOODYN_WRAP(woort_pop)                                                  \
    WOODYN_WRAP(woort_internal_value)                                       \
    WOODYN_WRAP(woort_import_value)                                         \
    WOODYN_WRAP(woort_bootup)                                               \
    WOODYN_WRAP(woort_invoke)                                               \
    WOODYN_WRAP(woort_spawn)                                                \
    WOODYN_WRAP(woort_resume)                                               \
    WOODYN_WRAP(woort_load_const)                                           \
    WOODYN_WRAP(woort_load_extern_const)                                    \
    WOODYN_WRAP(woort_set_value)                                            \
    WOODYN_WRAP(woort_set_dup_boxed)                                        \
    WOODYN_WRAP(woort_set_nil)                                              \
    WOODYN_WRAP(woort_set_int)                                              \
    WOODYN_WRAP(woort_set_real)                                             \
    WOODYN_WRAP(woort_set_float)                                            \
    WOODYN_WRAP(woort_set_bool)                                             \
    WOODYN_WRAP(woort_set_string)                                           \
    WOODYN_WRAP(woort_set_string_fmt)                                       \
    WOODYN_WRAP(woort_set_buffer)                                           \
    WOODYN_WRAP(woort_set_vec)                                              \
    WOODYN_WRAP(woort_set_map)                                              \
    WOODYN_WRAP(woort_set_struct)                                           \
    WOODYN_WRAP(woort_set_gchandle)                                         \
    WOODYN_WRAP(woort_set_gcstruct)                                         \
    WOODYN_WRAP(woort_set_box_int)                                          \
    WOODYN_WRAP(woort_set_box_real)                                         \
    WOODYN_WRAP(woort_set_box_bool)                                         \
    WOODYN_WRAP(woort_set_union_without_value)                              \
    WOODYN_WRAP(woort_set_union_value)                                      \
    WOODYN_WRAP(woort_set_union_nil)                                        \
    WOODYN_WRAP(woort_set_union_int)                                        \
    WOODYN_WRAP(woort_set_union_real)                                       \
    WOODYN_WRAP(woort_set_union_float)                                      \
    WOODYN_WRAP(woort_set_union_bool)                                       \
    WOODYN_WRAP(woort_set_union_string)                                     \
    WOODYN_WRAP(woort_set_union_string_fmt)                                 \
    WOODYN_WRAP(woort_set_union_buffer)                                     \
    WOODYN_WRAP(woort_set_union_vec)                                        \
    WOODYN_WRAP(woort_set_union_map)                                        \
    WOODYN_WRAP(woort_set_union_struct)                                     \
    WOODYN_WRAP(woort_set_union_gchandle)                                   \
    WOODYN_WRAP(woort_set_union_gcstruct)                                   \
    WOODYN_WRAP(woort_set_union_box_int)                                    \
    WOODYN_WRAP(woort_set_union_box_real)                                   \
    WOODYN_WRAP(woort_set_union_box_bool)                                   \
    WOODYN_WRAP(woort_ret_panic)                                            \
    WOODYN_WRAP(woort_ret_yield)                                            \
    WOODYN_WRAP(woort_int)                                                  \
    WOODYN_WRAP(woort_real)                                                 \
    WOODYN_WRAP(woort_float)                                                \
    WOODYN_WRAP(woort_bool)                                                 \
    WOODYN_WRAP(woort_string)                                               \
    WOODYN_WRAP(woort_buffer)                                               \
    WOODYN_WRAP(woort_gcpointer)                                            \
    WOODYN_WRAP(woort_unbox_int)                                            \
    WOODYN_WRAP(woort_unbox_real)                                           \
    WOODYN_WRAP(woort_unbox_bool)                                           \
    WOODYN_WRAP(woort_unbox_type)                                           \
    WOODYN_WRAP(woort_unbox)                                                \
    WOODYN_WRAP(woort_union_get)                                            \
    WOODYN_WRAP(woort_vec_len)                                              \
    WOODYN_WRAP(woort_vec_resize)                                           \
    WOODYN_WRAP(woort_vec_resize_with)                                      \
    WOODYN_WRAP(woort_vec_shrink)                                           \
    WOODYN_WRAP(woort_vec_get)                                              \
    WOODYN_WRAP(woort_vec_set)                                              \
    WOODYN_WRAP(woort_vec_push)                                             \
    WOODYN_WRAP(woort_vec_pop)                                              \
    WOODYN_WRAP(woort_vec_insert)                                           \
    WOODYN_WRAP(woort_vec_erase)                                            \
    WOODYN_WRAP(woort_vec_clear)                                            \
    WOODYN_WRAP(woort_vec_copy)                                             \
    WOODYN_WRAP(woort_vec_swap)                                             \
    WOODYN_WRAP(woort_map_len)                                              \
    WOODYN_WRAP(woort_map_reserve)                                          \
    WOODYN_WRAP(woort_map_get)                                              \
    WOODYN_WRAP(woort_map_get_by_int)                                       \
    WOODYN_WRAP(woort_map_get_by_real)                                      \
    WOODYN_WRAP(woort_map_get_by_bool)                                      \
    WOODYN_WRAP(woort_map_get_by_string)                                    \
    WOODYN_WRAP(woort_map_set)                                              \
    WOODYN_WRAP(woort_map_set_by_int)                                       \
    WOODYN_WRAP(woort_map_set_by_real)                                      \
    WOODYN_WRAP(woort_map_set_by_bool)                                      \
    WOODYN_WRAP(woort_map_set_by_string)                                    \
    WOODYN_WRAP(woort_map_erase)                                            \
    WOODYN_WRAP(woort_map_erase_by_int)                                     \
    WOODYN_WRAP(woort_map_erase_by_real)                                    \
    WOODYN_WRAP(woort_map_erase_by_bool)                                    \
    WOODYN_WRAP(woort_map_erase_by_string)                                  \
    WOODYN_WRAP(woort_map_clear)                                            \
    WOODYN_WRAP(woort_map_copy)                                             \
    WOODYN_WRAP(woort_map_swap)                                             \
    WOODYN_WRAP(woort_map_contains)                                         \
    WOODYN_WRAP(woort_map_contains_int)                                     \
    WOODYN_WRAP(woort_map_contains_real)                                    \
    WOODYN_WRAP(woort_map_contains_bool)                                    \
    WOODYN_WRAP(woort_map_contains_string)                                  \
    WOODYN_WRAP(woort_map_iter)                                             \
    WOODYN_WRAP(woort_serialize_dynbox)                                     \
    WOODYN_WRAP(woort_serialize_map)                                        \
    WOODYN_WRAP(woort_serialize_vec)                                        \
    WOODYN_WRAP(woort_deserialize_dynbox)                                   \
    WOODYN_WRAP(woort_deserialize_map)                                      \
    WOODYN_WRAP(woort_deserialize_vec)                                      \
    WOODYN_WRAP(woort_struct_len)                                           \
    WOODYN_WRAP(woort_struct_get)                                           \
    WOODYN_WRAP(woort_struct_set)                                           \
    WOODYN_WRAP(woort_struct_get_int)                                       \
    WOODYN_WRAP(woort_struct_get_real)                                      \
    WOODYN_WRAP(woort_struct_get_string)                                    \
    WOODYN_WRAP(woort_struct_get_bool)                                      \
    WOODYN_WRAP(woort_struct_set_int)                                       \
    WOODYN_WRAP(woort_struct_set_real)                                      \
    WOODYN_WRAP(woort_struct_set_string)                                    \
    WOODYN_WRAP(woort_struct_set_bool)                                      \
    WOODYN_WRAP(woort_exe_path)                                             \
    WOODYN_WRAP(woort_set_exe_path)                                         \
    WOODYN_WRAP(woort_work_path)                                            \
    WOODYN_WRAP(woort_set_work_path)                                        \
    WOODYN_WRAP(woort_get_file_loc)                                         \
    WOODYN_WRAP(woort_normalize_path)                                       \
    WOODYN_WRAP(woort_vfs_create)                                           \
    WOODYN_WRAP(woort_vfs_remove)                                           \
    WOODYN_WRAP(woort_vfs_is_virtual_uri)                                   \
    WOODYN_WRAP(woort_vfs_exists)                                           \
    WOODYN_WRAP(woort_vfs_get_all_paths)                                    \
    WOODYN_WRAP(woort_fs_is_file_readable)                                  \
    WOODYN_WRAP(woort_vfs_resolve_path)                                     \
    WOODYN_WRAP(woort_vfile_open)                                           \
    WOODYN_WRAP(woort_vfile_open_reader)                                    \
    WOODYN_WRAP(woort_vfile_read)                                           \
    WOODYN_WRAP(woort_vfile_seek)                                           \
    WOODYN_WRAP(woort_vfile_tell)                                           \
    WOODYN_WRAP(woort_vfile_size)                                           \
    WOODYN_WRAP(woort_vfile_close)                                          \
    WOODYN_WRAP(woort_dylib_fake)                                           \
    WOODYN_WRAP(woort_dylib_load)                                           \
    WOODYN_WRAP(woort_dylib_load_func)                                      \
    WOODYN_WRAP(woort_dylib_get_func_name)                                  \
    WOODYN_WRAP(woort_dylib_unload)                                         \
    WOODYN_WRAP(woort_dylib_keep)                                           \
    WOODYN_WRAP(woort_get_builtin_lib)                                      \
    WOODYN_WRAP(woort_WAIPO_Debugger_attach)                                \
    WOODYN_WRAP(woort_WAIPO_Debugger_do_get_current_vm)                     \
    WOODYN_WRAP(woort_WAIPO_Debugger_do_get_current_frame)                  \
    WOODYN_WRAP(woort_WAIPO_Debugger_do_switch_trace_frame)                 \
    WOODYN_WRAP(woort_WAIPO_Debugger_do_get_local_count)                    \
    WOODYN_WRAP(woort_WAIPO_Debugger_do_query_local)                        \
    WOODYN_WRAP(woort_WAIPO_Debugger_do_get_variable_by_name)               \
    WOODYN_WRAP(woort_WAIPO_Debugger_set_source_breakpoint)                 \
    WOODYN_WRAP(woort_WAIPO_Debugger_set_function_breakpoint)               \
    WOODYN_WRAP(woort_WAIPO_Debugger_query_breakpoints)                     \
    WOODYN_WRAP(woort_WAIPO_Debugger_get_breakpoint_info)                   \
    WOODYN_WRAP(woort_WAIPO_Debugger_delete_breakpoint)                     \
    WOODYN_WRAP(woort_WAIPO_Debugger_clear_breakpoint)                      \
    WOODYN_WRAP(woort_VMRuntime_Debugger_query_vms)                         \
    WOODYN_WRAP(woort_VMRuntime_Debugger_try_breakdown_any_vm)              \
    WOODYN_WRAP(woort_VMRuntime_Debugger_try_breakdown_vm)                  \
    WOODYN_WRAP(woort_VMRuntime_Debugger_terminate_all_vm)                  \
    WOODYN_WRAP(woort_VMRuntime_Debugger_try_terminate_vm)                  \
    WOODYN_WRAP(woort_VMRuntime_Debugger_serialize_value)                   \
    WOODYN_WRAP(woort_ctrlc_setup)                                          \
    WOODYN_WRAP(woort_ctrlc_teardown)                                       \
    WOODYN_WRAP(woort_set_panic_callback)                                   \
    WOODYN_WRAP(woort_str_get_char)                                         \
    WOODYN_WRAP(woort_strn_get_char)                                        \
    WOODYN_WRAP(woort_str_to_wstr)                                          \
    WOODYN_WRAP(woort_strn_to_wstr)                                         \
    WOODYN_WRAP(woort_wstr_to_str)                                          \
    WOODYN_WRAP(woort_wstrn_to_str)                                         \
    WOODYN_WRAP(woort_str_to_u16str)                                        \
    WOODYN_WRAP(woort_strn_to_u16str)                                       \
    WOODYN_WRAP(woort_u16str_to_str)                                        \
    WOODYN_WRAP(woort_u16strn_to_str)                                       \
    WOODYN_WRAP(woort_str_to_u32str)                                        \
    WOODYN_WRAP(woort_strn_to_u32str)                                       \
    WOODYN_WRAP(woort_u32str_to_str)                                        \
    WOODYN_WRAP(woort_u32strn_to_str)                                       \
    WOODYN_WRAP(woort_u8charnlen)                                           \
    WOODYN_WRAP(woort_u8strnlen)                                            \
    WOODYN_WRAP(woort_u8strnchar)                                           \
    WOODYN_WRAP(woort_u8substr)                                             \
    WOODYN_WRAP(woort_u8substrr)                                            \
    WOODYN_WRAP(woort_u8substrn)                                            \
    WOODYN_WRAP(woort_u8combineu32)                                         \
    WOODYN_WRAP(woort_u32exractu8)                                          \
    WOODYN_WRAP(woort_u8combineu16)                                         \
    WOODYN_WRAP(woort_u16exractu8)                                          \
    WOODYN_WRAP(woort_u16hisurrogate)                                       \
    WOODYN_WRAP(woort_u16losurrogate)                                       \
    WOODYN_WRAP(woort_u8enstring)                                           \
    WOODYN_WRAP(woort_u8destring)                                           \
    WOODYN_WRAP(woort_u8strtou32)                                           \
    WOODYN_WRAP(woort_u32strtou8)                                           \
    WOODYN_WRAP(woort_u8strtou16)                                           \
    WOODYN_WRAP(woort_u16strtou8)                                           \
    WOODYN_WRAP(woort_u16strcount)                                          \
    WOODYN_WRAP(woort_u32strcount)                                          \
    WOODYN_WRAP(woort_u32isu16)                                             \
    WOODYN_WRAP(woort_u8stridx)                                             \
    WOODYN_WRAP(woort_REPLPrinter_create)                                   \
    WOODYN_WRAP(woort_REPLPrinter_destroy)                                  \
    WOODYN_WRAP(woort_REPLPrinter_flush)

static woort_Dylib* _s_libwoort_woodyn = NULL;
static const woort_ExternLibFunc _s_libwoort_woodyn_funcs[] = {
#define WOODYN_WRAP(F) {#F, (void*)&F},
    WOODYN_WOORT_FUNCTION_LIST
#undef WOODYN_WRAP
    WOORT_EXTERN_LIB_FUNC_END
};

WOORT_NODISCARD bool woort_woodyn_init(void)
{
    if (_s_libwoort_woodyn == NULL)
    {
        if (!_woort_dylib_bootup())
            return false;

        _s_libwoort_woodyn = woort_dylib_fake(
            "libwoort_woodyn",
            _s_libwoort_woodyn_funcs,
            NULL);
    }
    return true;
}

void woort_woodyn_shutdown(void)
{
    if (_s_libwoort_woodyn != NULL)
    {
        woort_dylib_unload(
            _s_libwoort_woodyn,
            WOORT_DYLIB_UNREF_AND_BURY);

        _s_libwoort_woodyn = NULL;

        _woort_dylib_shutdown();
    }
}