#pragma once

/*
woort_ir_op.h
*/

#include <stdint.h>
#include <stddef.h>

#include "woort_ir_value.h"

typedef enum woort_IROp_Kind
{
    WOORT_IROP_KIND_LOAD,
    WOORT_IROP_KIND_STORE,

    WOORT_IROP_KIND_PUSHCHK,
    WOORT_IROP_KIND_POP,
    WOORT_IROP_KIND_POPR,
    WOORT_IROP_KIND_POPRS,

    WOORT_IROP_KIND_ITOR,
    WOORT_IROP_KIND_ITOS,
    WOORT_IROP_KIND_RTOI,
    WOORT_IROP_KIND_RTOS,
    WOORT_IROP_KIND_STOI,
    WOORT_IROP_KIND_STOR,

    WOORT_IROP_KIND_CALLNWO,
    WOORT_IROP_KIND_CALLNFP,
    WOORT_IROP_KIND_CALLNJIT,
    WOORT_IROP_KIND_CALL,

    WOORT_IROP_KIND_MKVEC,
    WOORT_IROP_KIND_MKMAP,
    WOORT_IROP_KIND_MKSTRUCT,

    WOORT_IROP_KIND_BOXDYN,
    WOORT_IROP_KIND_UNBOXDYN,
    WOORT_IROP_KIND_CHECKDYN,
    WOORT_IROP_KIND_PUSHBOXDYN,

    WOORT_IROP_KIND_ADDI,
    WOORT_IROP_KIND_SUBI,
    WOORT_IROP_KIND_MULI,
    WOORT_IROP_KIND_DIVI,
    WOORT_IROP_KIND_MODI,
    WOORT_IROP_KIND_NEGI,
    WOORT_IROP_KIND_LTI,
    WOORT_IROP_KIND_GTI,
    WOORT_IROP_KIND_LEI,
    WOORT_IROP_KIND_GEI,
    WOORT_IROP_KIND_EQI,
    WOORT_IROP_KIND_NEI,

    WOORT_IROP_KIND_ADDR,
    WOORT_IROP_KIND_SUBR,
    WOORT_IROP_KIND_MULR,
    WOORT_IROP_KIND_DIVR,
    WOORT_IROP_KIND_MODR,
    WOORT_IROP_KIND_NEGR,
    WOORT_IROP_KIND_LTR,
    WOORT_IROP_KIND_GTR,
    WOORT_IROP_KIND_LER,
    WOORT_IROP_KIND_GER,
    WOORT_IROP_KIND_EQR,
    WOORT_IROP_KIND_NER,

    WOORT_IROP_KIND_ADDS,
    WOORT_IROP_KIND_LTS,
    WOORT_IROP_KIND_GTS,
    WOORT_IROP_KIND_LES,
    WOORT_IROP_KIND_GES,
    WOORT_IROP_KIND_EQS,
    WOORT_IROP_KIND_NES,

    WOORT_IROP_KIND_LAND,
    WOORT_IROP_KIND_LOR,
    WOORT_IROP_KIND_LNOT,

    WOORT_IROP_KIND_LDIDXVEC,
    WOORT_IROP_KIND_LDIDXVECX,
    WOORT_IROP_KIND_LDIDXSTRUCT,
    WOORT_IROP_KIND_LDIDXSTRING,

    WOORT_IROP_KIND_LDIDXDICTI,
    WOORT_IROP_KIND_LDIDXDICTR,
    WOORT_IROP_KIND_LDIDXDICTB,
    WOORT_IROP_KIND_LDIDXDICTX,

    WOORT_IROP_KIND_SDIDXVECI,
    WOORT_IROP_KIND_SDIDXVECR,
    WOORT_IROP_KIND_SDIDXVECB,
    WOORT_IROP_KIND_SDIDXVECX,

    WOORT_IROP_KIND_SDIDXDICTII,
    WOORT_IROP_KIND_SDIDXDICTIR,
    WOORT_IROP_KIND_SDIDXDICTIB,
    WOORT_IROP_KIND_SDIDXDICTIX,
    WOORT_IROP_KIND_SDIDXDICTRI,
    WOORT_IROP_KIND_SDIDXDICTRR,
    WOORT_IROP_KIND_SDIDXDICTRB,
    WOORT_IROP_KIND_SDIDXDICTRX,
    WOORT_IROP_KIND_SDIDXDICTBI,
    WOORT_IROP_KIND_SDIDXDICTBR,
    WOORT_IROP_KIND_SDIDXDICTBB,
    WOORT_IROP_KIND_SDIDXDICTBX,
    WOORT_IROP_KIND_SDIDXDICTXI,
    WOORT_IROP_KIND_SDIDXDICTXR,
    WOORT_IROP_KIND_SDIDXDICTXB,
    WOORT_IROP_KIND_SDIDXDICTXX,

    WOORT_IROP_KIND_SDIDXMAPII,
    WOORT_IROP_KIND_SDIDXMAPIR,
    WOORT_IROP_KIND_SDIDXMAPIB,
    WOORT_IROP_KIND_SDIDXMAPIX,
    WOORT_IROP_KIND_SDIDXMAPRI,
    WOORT_IROP_KIND_SDIDXMAPRR,
    WOORT_IROP_KIND_SDIDXMAPRB,
    WOORT_IROP_KIND_SDIDXMAPRX,
    WOORT_IROP_KIND_SDIDXMAPBI,
    WOORT_IROP_KIND_SDIDXMAPBR,
    WOORT_IROP_KIND_SDIDXMAPBB,
    WOORT_IROP_KIND_SDIDXMAPBX,
    WOORT_IROP_KIND_SDIDXMAPXI,
    WOORT_IROP_KIND_SDIDXMAPXR,
    WOORT_IROP_KIND_SDIDXMAPXB,
    WOORT_IROP_KIND_SDIDXMAPXX,

    WOORT_IROP_KIND_SDIDXSTRUCT,

    WOORT_IROP_KIND_UNPACKSTRUCT,
    WOORT_IROP_KIND_UNPACKVEC,
    WOORT_IROP_KIND_UNPACKVECX,

    WOORT_IROP_KIND_PUSHIDXSTRUCT,
    WOORT_IROP_KIND_PUSHIDXSTBOXI,
    WOORT_IROP_KIND_PUSHIDXSTBOXR,
    WOORT_IROP_KIND_PUSHIDXSTBOXB,
    WOORT_IROP_KIND_PUSHIDXSTBOXX,

} woort_IROp_Kind;

struct woort_IROp
{
    woort_IROp_Kind m_op;

    /* OPTIONAL */ const woort_IRValue* m_r[3];
    /* OPTIONAL */ const woort_IRValue* m_w;

    union
    {
        woort_IRStaticIndex m_static_index;
        uint32_t m_count;
        uint32_t m_index;
        uint8_t m_type;
        struct
        {
            woort_IRConstantIndex m_calln_target;
            uint32_t m_argument_count;
        };
    };

};
